---
title: Il blocco ' Catch ' non è mai stato raggiunto perché' <name1> ' eredita da' <name2> '
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 560beddd1e9051c43d610fe893a55baa2a5c559a
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 06/04/2020
ms.locfileid: "84395649"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>Il blocco ' Catch ' non è mai stato raggiunto perché' \<name1> ' eredita da' \<name2> '
Un blocco `Catch` all'interno del codice non viene mai raggiunto.  
  
 Per impostazione predefinita, si tratta di un messaggio di avviso. Per altre informazioni su come nascondere gli avvisi o considerarli come errori, vedere [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **ID errore:** BC42029  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
- Rimuovere il blocco `Catch` estraneo.  
  
## <a name="see-also"></a>Vedere anche

- [Come usare il blocco try/catch per rilevare le eccezioni](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Istruzione Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
